### PR TITLE
Update Cursive integration instructions

### PR DESCRIPTION
**Pull request by SergeyKozachenko**
I found these instructions are a bit off. This PR to fix it to the current state.

### CODE REVIEW

**Comment by thheller** [comment]
No, the current instructions are accurate. You should NEVER touch the manual Cursive Select Box.

**Comment by SergeyKozachenko** [comment]
@thheller Sorry, if I am missing something, but this is what I get if I try to follow the original instructions:
image

**Comment by thheller** [comment]
Ok, so the REPL is in CLJ mode. The Cursive error in the first screenshot is telling you that you cannot eval CLJS in a CLJ REPL. This is correct. The `(shadow/repl :app)` command is a CLJ command but you have it in a `.cljs` file which doesn't work.

So instead type that manually directly into the REPL input. You'll see that the Cursive select box automatically switches to CLJS. From that on you can eval CLJS directly from `.cljs` files.

**Comment by SergeyKozachenko** [comment]
@thheller Ok, but still, what I did was:

1. Run `npx shadow-cljs server` in my root proj dir
2. Start remote nREPL 

image

It's not allowing to type directly in Cursive Remote REPL:
image

**Comment by SergeyKozachenko** [comment]
Nevermind, this is a bummer, it appears I had the input section moved to the bottom and so I forgot it exists:
image

**Pull request closed without merging**
